//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class IAControl : Control {
		GameObject gameObject;

		// Decisions
		bool goRight;
		bool goLeft;
		bool speedUp;
		bool slowDown;

		public IAControl (GameObject gameObject) {
			this.gameObject = gameObject;
		}

		public override bool TurningRight() {
			return goRight;
		}

		public override bool TurningLeft() {
			return goLeft;
		}

		public override bool Accelerating() {
			return speedUp;
		}

		public override bool Slowing() {
			return slowDown;
		}

		public void UpdateDecision() {
			goRight = false;
			goLeft = false;
			speedUp = true;
			slowDown = false;
		}
	}
}
