//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp {
	public class Keyboard : Control {

		public override bool TurningRight() {
			return Input.GetKeyDown (KeyCode.RightArrow); 
		}

		public override bool TurningLeft() { 
			return Input.GetKeyDown (KeyCode.RightArrow);
		}

		public override bool Accelerating() { 
			return Input.GetKeyDown (KeyCode.UpArrow);
		}

		public override bool Slowing() { 
			return Input.GetKeyDown (KeyCode.DownArrow);
		}
	}

}

