//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp {
	public class Keyboard : Control {

		public Keyboard (Movement parent) : base (parent) {}

		public override bool TurningRight() {
			return Input.GetKey(KeyCode.RightArrow); 
		}

		public override bool TurningLeft() { 
			return Input.GetKey(KeyCode.LeftArrow);
		}

		public override bool Accelerating() { 
			return Input.GetKey(KeyCode.UpArrow);
		}

		public override bool Slowing() { 
			return Input.GetKey(KeyCode.DownArrow);
		}
	}

}

